---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: freshrss
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: freshrss
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
