apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:DgSJjN1xT51qplYUOhNuPFPE6Td4LtVI+dFxsNgF+EV70GFuBd6vttmzNQcsS1pXkmk4UfXwyprOl+c474DebGhhmHEU1y9nJVLcvN+E/J36e54pGGSFDvMtHLXWFHZ74NetIdhEcbWtrVtU8gWvIIgFd5K5AHKmq4Vsf39rG1eRudwrkufPNFbBVd5dFH2LFy1QEqAPy8cS0q0zeOS+lqjse1LtQcTZhWadWVlhVhmGK/8PowN8rvblb5xcN2QxzDEYT0cvjMdBBWtxeB9mF6gFCglPtD8IbIw9nntXtJ/Wpj85WYYU6Xeb0XUTfbUFjB8l0G9oyJ/LNTD2GA5+O+UL3h2l/fGz+TFitbPPkCLQhQZjvfCITiYamIjS0oeviWs2l205LXQJoU+dc2oQg3Vyt3weH0Bt3lJQg+6wv/Dr74ex5V85olYF79If7vyvX/2yzj5PiHY86/XsTfKM1CQ8uAGckWT+HAi8n+HYUU3+8BGp,iv:Vi0neocLG21gd+OVPrpzsjRgtBDWAKkmzTt5/2rMr8Q=,tag:aEgLcOp91LFr5+TYkwIz3g==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:lqBOCG6+lxZssnUiy4D0oJLCBCAcTHRh32SsYZIOSLyff2ghYc+9qjRGYHY278b1sJSEKckbMOjzobInnHLg/YAFETrBnayUaLACN2dHbIzZ8zYaLwMyU76iot6AdGyO2zcJxxQjqmfwBMVx05zeF2erCnlFejLNNVmtQSjtCsVlHmGdop2YEobsFaYw8Q0Y72s98RMC7srwB7mbi8Yyzmuof74=,iv:dd/tac867/NbQL4mgMwfuIcpb3ub1/OjrwWO7X6whyU=,tag:dYWJdwAwcXZuGPZsgw1HZQ==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:U07wtImnSzYCu2FejkzEopQN9kUZ202cyefclyovMNLVpRXQqOHgvGe+h+XjFvYf4vQeiD1DO0UehdzYs2RacDnoSp35H658FPysQMBh+Fil01km9FWs02oqMLLR1J2fpvY1ODbdvQRK7RJPCkQjEV06E0QlSZCDmzE61dD3LJP7HhO2bL5t3N2K2+7DodqvzIIYWVXah9EmD7myg9oPNAtRvg==,iv:mxwYepi9bMng+NxoWcQZb6dGdkNnAS2/5EfkPPIX0Bc=,tag:q43+VZ5Pfsvd88V7gMwtjg==,type:str]
    auth.yml: ENC[AES256_GCM,data:RakpMs9AKFmWCMdBSz9R3+LkHxIFMkKw0qMznFJttd2HQWZG0A1ERp6SojSGYqvksascADIuXsIyQQ==,iv:v6pxBJ71nbYLL1V6dltB3bzjyqyWt2S6l9JSwR43Vkg=,tag:9brpXSjwethaK04TGqSJLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbzJ5ViszNTZ6ajJ0Rk9v
            aHBISUJ0UmNMNGhRbDM3Qm1XQi9DUFpzWVNRCkhWQk9WQmRWL1JTN0g5UUJJZlEr
            MW9nblJKSjJWNkdvVWJqaVFabUVQZWMKLS0tIDJ0eHE2c1gyQTFlbWkzV2lRMUEv
            VHI3bnRrd0s4Q3dLYnNweUgwVVRlVzgKq0GiidaFjtx/n4UyettiR2ckpB+qUV6i
            v5BbD6Geu3MOW6AGhRlQAc8b2aFyQvvv+jqo7IXVelIoePf2KWCjwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T20:04:51Z"
    mac: ENC[AES256_GCM,data:BJJkU0yc60hkm27dIqITPU4wxenH+YN2KzOdyeXM3DIfZ4VLQWjz2j9bAh14E0N+Pmf3p+6OiOnTD/KFOygdfKIXdYsM4gwhUo0ml9ib5zEGBkDbm6f88ef/lQq3xUEpWJPcs0JXcW7FjAE4Wx8NCkvjBTFqw2gE9uUfosHPjVU=,iv:8fO9hMjeqfxoOYyc7h6EWYYp1wHH44HVlN6G6SWJq2s=,tag:Vt60S0pT512SvT93JhAlbQ==,type:str]
    version: 3.13.2
