apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:TukSOuKj4bDvt3CW2BOy9k009y82/OhIRnwG7g0j6qPjklkgEFoxwiZT7EZU0wPZ6obbmARu00Ev0OY1OsJ0FqRLYAhbSgnZXfCuA1WFr550dUxNIwwyS+z0LnrXFVghrLsSYwXpG5aEHd9kTKbVwF1MJYIXyDd/UhE8/bUHOuJh2Hf+F5sAnLJRU80PLJmL5tFjzduIUyhxgQta30RvhVWeaYY7DxfVurCJz6P15BVsR06bTNf3pDUTqYEMzK0cHqlbj4xAqjiP46CQmUUG/K3Qzk2oTmM0cRkrA9296cQWnNsR9ccoQwWqj0vxiKnXXrK+f+TSi+1TRicVLIeL8LFQ9GLJaeNO29g97PtAei/wOQMCAb9pfo51XAEkERk0zCROKTbZI2bjZqhTAT4PVd624QyBk0nxdoOG9yoHEW58Fk/mtwWH8IWNLz82HCt81EehfZx6zosXtk5JXPvrboJeSehRfzPETZ6r2UvCeZuwuaP4Mfi0B8Pr/Q==,iv:vQW7yUGqwCDwwQu/CQcpr9utA8OJFaP0JWGnyVamsqI=,tag:hLJmj4+8HBNZprPnoe1LIA==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:DwAlydI9dJZ2zICbtzl9zOnnZZK5Iim85PsQM58H8vmDprADzbOMdAyUgPyxumHwh5RpsPMSz/YCXPRR20vjdOAzYf4PeSFWnMgWt3bECd2fw9v80kwsYD4eRfDqWUFNZeC3zWyhVrBSr89bUeZi5Ar948nbPeMWAJbHQ4n8xa6ZlGn7HxnZvXs8n6ppZdp0IrZiEgwFLA32i2vogcA53VL1l9Pvez8nb2Qx,iv:+xxwwhoYHyIleq8+uXuSdwgi1NVviEkViWA2vXaekeI=,tag:rObAHZTfn4+jPKqmKTjgcg==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:MaGZOuiFg7rK36v3PFA+MNUYOF64V6MJOmSRrViEQGfmB1x2qVkTi0EyW0sz1T4O30gJ1YqK8kqUpbISSw2Vk/L5D9eGei6YkkKIfu4M1TTNVxNCrUQrLdmoFB8JE4j6ZjmwDXKye+nkFk224yVetXA1Xr8LH0UxHnyFAWz5ZoYqo9qkeD1tr9L28rDHor9tJjwZGtsNnA2sfQN5pG3NR6h7YTtFHlsLxeo=,iv:SzHzqiNLBccjCWa/Xefl6YWpXH1eBpHrUgcBOVyVaDM=,tag:+9mpfRp5r5tg12++XyKKWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVVloRlA2clRrRk5oYlFa
            M2tldVo2YTk2Q0tNRU5ieVVsWDhyeGdFUjNRClEwalhOcXgwRzlKZEhCZ0Z1MmVY
            M0c0NSt0UlpGRXZ0V3VtNzdXNU9aK1UKLS0tIE9UMXpzclE5ckJpOTBLSlRwKzl1
            U0VVbHJtV1ppSVVFY1RFRzB0Mmh0NjgKvLetUkvYNEAe5nAbQV3pkt5JOw+h7hwx
            p+9SrTWLGz9+yFdHWhR5DVBx6aRyGpPPRFWlI6bssPX/JOmJY4macQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T21:44:08Z"
    mac: ENC[AES256_GCM,data:5j5/vJpvNzaSegpai8z6Mve/MiJo6z8RTPYj2elE4cJqKAg+b1EQ9W2RNFhYY8DzX9anMzPErA2DndWivKKMA1SS5vfX5yL/Wt9SN8rIgn44ATfuTUnC0hsfGGOclZZM6HdSgXPre5e4O/uzwFoNS0LctZLDUpBHzwCmvNmM5YI=,iv:Eff8hcb13KFLc7jVU7LMVV3JWihJDN7v0prWxL0fmiA=,tag:PRLR3zle3hzaFmK+NHf+fg==,type:str]
    version: 3.13.2
