apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secret
    namespace: ntfy
type: Opaque
stringData:
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:nAieUMXuZyDOnEgfzr8ftyMhUBN80VbDoTXg996koek2ANCIUnJXBnFSnNpxK112m9NtoU+PumZu/jAmKDvkPB902wHVFyZFF2pgxJDsv2sWvMqy/hqeGq4Huz0+SSSJz/mH3Wx4XOPDh+FyPmaHskVzi6+FHriwXDOlWXLNqWBmcT9N656TNMgW/n8DyNiR79UWRVBWYwknOvqJ8KnoCe162p5sfn+9xXXquOKCsxmL+a6lgEubgqHnD/cQG4YjrNsYsymEatgaSgF0+gaGvW3ixguhU7k3Y+a8d0uSf2wLPx43Uyhqaw5g7sf9uOVdmKUvuJSX77SrV3nQ5scGepNLVJlorgL+TUdUI39tIa/2BQGCPAEkEa2zeOl/IXAiOw9tT+cFsbEvMbf3iqO2eQ==,iv:c/SUmtMAiXOz3BIcyGC1AogzOHc36vl9OeyymynQPj8=,tag:ZnIygPeQrW1GsCNVaZ8zaw==,type:str]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:3216GGTpZhtMskX3TtNYAWF6NHh+4zABzmnEEz0vlvY3LcvN3YF40UmQxadYt3//TiiJxKn83TOUxO9MNMayV3S4QECeUDRwG1H15A9aBWlHdLP4YXmtCe7P+8ue/dEe11KSONoMpJYwq+aith6icWE7o4Aux54EIi++HikOS91sCbM2J+bQ7Z0ElM9aZTDZmxmVkIpL,iv:TnXVh8Da2Kuuz55N7BC6PdDwM6B0TAzA1++LiWWQ89Q=,tag:9+Y8ufMyF0ujFfRmVB6g8w==,type:str]
    NTFY_AUTH_TOKENS: ENC[AES256_GCM,data:CZ0RadQhcKhFk4IqZLjuLkdWSFRq4JeSbUu3q6/YUteCMWz04Gok8XbjZwYT4O12IO4ZNu7ruBoUy1rDR9MiwkQxRtjMwv46ijR0sZrE/+ucXfzypZXf+IJRv2OY4lg+C8Iy/AgcJQMAae51e/Gy1u9Lmef3RWxZGCpbV8P1k6w=,iv:vx77eso1XvFfoAiA8IWy87V9nGHXzy4gkxoHKuw9cdI=,tag:MSZdinDdeJr8ITHmlgyP2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aVpPQTdMUHlxZU5ETTNu
            dmcyb2ZZbm5Vamx1ajM4MUVUSE5yN0Q2NW5vCkNGQmhpUHFxNG5DYVhtZVZ4UWRs
            WWkvcnNuQzNkc04wTlpOei96dUVSWXcKLS0tIHJvaU96NUUrNkdOMmM0UWM0T2Yr
            SmhYdlZURkt1aWhtU2FRT1lmVVRNeEEKWQjxSaiTpYQyjNNtny42ma/EZEjwO2fe
            lXNEswbmfM6MOu+YNVW5aeP52mR4EN/03NUw/6zkEm6d0Usz3gXonQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T19:59:10Z"
    mac: ENC[AES256_GCM,data:VS5nzSXZh3PocuW6mefmFIf+bjTxY4Gzc5R9RFEt31fcgjxwSyRFXp/srjwd6zhQtKvZlpf0zpNfvi6GUuz5mWR8jt6veY/1V2Y9reuaRharfOFNVBtCYdG6IPvVc9TINa20jh8CM5b+4kvpPBcQ9dql5BIsOdgrsY1ofKclnQw=,iv:UlkKsrUpaHDZv6sV7sl172VYacBLwQOCRnhACzIzp9s=,tag:ib4/fxg5zlcARaELVB6IxA==,type:str]
    version: 3.13.2
