---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproute.yaml
  - ./namespace.yaml
  - ./portainer-admin-password.sops.yaml
  - ./prometheusrule.yaml
  - ./rbac.yaml
configMapGenerator:
  - name: portainer-values
    namespace: portainer
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
