apiVersion: v1
kind: Secret
metadata:
    name: portainer-admin-password
    namespace: portainer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:mEf8i2h2KN3y/sHEijsaKt2QuO/M1c35S4f2cVMGOBnF1PsQdPEchw==,iv:g0PHN0/6tuZSED4r7DyXAWH78vNMy1h0WmqQBfPYhXY=,tag:GWm4mWL7aatpHD2XWYZrXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdnZrNE5BSFg4SXc2aEVw
            TlFnQkUxWnRMU2RIV25qc2hKdmVtRjh4VFYwCndTOGUxdGlDc1ZFL3EvL0V3djE0
            a1FSNnFhelduTWtQRGc5N2pOYnY1TGsKLS0tIC95TFFsRmNxN0tWcnBxbm1TNXdK
            dW5yMHhNaUpTT0V5a3RVbVh1RkxMdXcKeS5hrx7Vx5jCP82ux1wwnplINSdCa7zY
            Tfn2qDKL8k9Q9Jba5mfR45JEUqXmHwclRKBQXIf6Sy7/dlmx2ksauQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T01:48:03Z"
    mac: ENC[AES256_GCM,data:W+DuVnffsroa4YEZFLv7YSCIu8LGFzZuBwgzRNxbjrbkeAuNPwTv+86md3KwvvM0U7ATFhQOGYh4BRlb/j/lzy9BWV726pohTcjcahXLrchmYFQUcJXOTDlcUVLualXYFwApAS0Ob5BsSjcERkmvTtI9Lwxxk4J4lQcFpPp7aY8=,iv:yLsuEqXCnI56tUVYwoBMOD8vMZs1Vk3h6l9t4mJPzD4=,tag:s38R4asQklYJ4qPClRFajQ==,type:str]
    version: 3.13.2
