---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace/ks.yaml
  - ./storage/ks.yaml
  - ./encode-benchmark/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qbit-manage/ks.yaml
  - ./prowlarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./lidarr/ks.yaml
  - ./seerr/ks.yaml
  - ./tautulli/ks.yaml
  - ./alerts/ks.yaml
