---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
  - ./prometheusrule.yaml
  - ./ciliumnetworkpolicy.yaml
configMapGenerator:
  - name: plex-ddns-drift-config
    namespace: monitoring
    files:
      - Caddyfile=Caddyfile
      - check.sh=check.sh
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
