---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./campaign-lease.yaml
  - ./report-publication-lease.yaml
  - ./rbac.yaml
  - ./test-rbac.yaml
  - ./dedicated-rbac.yaml
  - ./dedicated-admission.yaml
  - ./node-reschedule-admission.yaml
  - ./openbao-test-admission.yaml
  - ./test-admission.yaml
  - ./restore-admission.yaml
  - ./restore-workload-admission.yaml
  - ./restore-network-admission.yaml
  - ./restore-extension-admission.yaml
  - ./provisioning-admission.yaml
  - ./network-probe-admission.yaml
