---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: news
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./persistentvolumeclaims.yaml
  - ./service.yaml
  - ./statefulset.yaml
configMapGenerator:
  - name: news-postgresql-init
    files:
      - init-news.sh=scripts/init-news.sh
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
