apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: news-postgresql-credentials
    namespace: news
stringData:
    postgres-superuser-password: ENC[AES256_GCM,data:LEJctKY4DizrwJJ77Ugrv2OOzSi5ybtZ/cRiAGN69Otdc5fTYs3yuA==,iv:HyYEH/WBXRIAA1tPvQ5n0l9JlDMtI1mXfLszpmTwY9o=,tag:prMXQkXasrN5xmt0sIZD0g==,type:str]
    freshrss-password: ENC[AES256_GCM,data:/XI4/8cpPMjnUwx4emS4t/daJMQQ3FftpG6o9j41VY7x5wtK1faP3A==,iv:1UWJSpNE9CQsPEbvYU39Ing0qehBSJ/KOKryJA86bmo=,tag:0+utZHaU1pXduzOr5qosog==,type:str]
    backup-password: ENC[AES256_GCM,data:9QGljq+lJ6MoT1bnek33xc1WKAVqX9O8Tu3n0y/fuskoEeiJiUCHBg==,iv:Ps+m2w3bv8exOB4GcdguUzhRM7UvRITV5niTbbOSKP4=,tag:0U7zxgmkXdUrAB4Gplsh8A==,type:str]
    monitoring-password: ENC[AES256_GCM,data:NH5G8iyEW7BRj1b3zF9HrmezQGGeXSMUscRZjYGFn5V7Hlg0c9V4mg==,iv:J6eJBQGMA6KamY/3N5Bo7Uwl+45lay6lNZxTYcRoa4E=,tag:MssR0YawjQgiO+YsA/SYgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eVRkRkxPS1ZGZDl2WUww
            SnNjeGNjajlxM0E2RUtpL21IWVM1ZnpSY2tVCmNqZ2tJS2VVbC82ejRrSXVLV0hK
            YlBRZ2E1N0ZUQThBbjZhSC92NzRmcHMKLS0tIG1FdGRSQVN6aVBVRE1oVkdDb0pQ
            amU5QjE1bmVpZHBURkwwejdtZnRpU0UKSGP0rP081NIYFJTEdG9jc8fnKbHdCZfD
            pLHP4JH3aP9PXMBh2WCk/qGGcFKrHKX07MPwe5ziqBJminc7USH/ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T15:31:31Z"
    mac: ENC[AES256_GCM,data:o66Uvy9a9p7bPgk/pAbgBFGsCvJgo93S6biUXKdVYuyBgpFXHH4NQSO7zNTjQCd9ClgDNx+EdQvSyVD9ClmE9lcm7CsVWX40yUNiNK80JIo8mo7BoY9Nl3R8aFIG1OFFYypfVEGrDFpMIaWpoqCmZPn/pABho60GeMMyiYn7Kr8=,iv:5eptTwm0x0gkjn2M+mxNuyYJEvOFEsYTn36rMP7WYRk=,tag:zyhvTwUXsOectx0177deaw==,type:str]
    version: 3.13.2
