---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gatus/ks.yaml
  - ./homepage/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./ntfy/ks.yaml
  - ./portainer/ks.yaml
  - ./test-reports/ks.yaml
