---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux.yaml
  - ./gatus.yaml
  - ./logging.yaml
  - ./n8n.yaml
  - ./ntfy.yaml
  - ./portainer.yaml
  - ./test-reports.yaml
