---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: freshrss-extraction-release
    files:
      - release.json=app/release.json
generatorOptions:
  immutable: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
