---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: crawl4ai-platform-runtime
    files:
      - credential_agent.py
      - server_launcher.py
      - config.yml
      - supervisord.conf
