[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
childlogdir=%(ENV_CRAWL4AI_RUNTIME_DIR)s

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 -::1 --protected-mode yes --requirepass "%(ENV_REDIS_PASSWORD)s" --dir "%(ENV_CRAWL4AI_RUNTIME_DIR)s" --save "" --appendonly no --maxmemory 64mb --maxmemory-policy noeviction --loglevel warning
directory=%(ENV_CRAWL4AI_RUNTIME_DIR)s
user=appuser
autorestart=unexpected
priority=10
stopsignal=TERM
stopwaitsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:gunicorn]
command=/usr/local/bin/gunicorn --bind 0.0.0.0:11235 --workers 1 --threads 4 --timeout 90 --graceful-timeout 10 --keep-alive 5 --log-level critical --limit-request-line 8190 --limit-request-fields 100 --worker-class uvicorn.workers.UvicornWorker server:app
directory=%(ENV_CRAWL4AI_RUNTIME_DIR)s
user=appuser
autorestart=unexpected
priority=20
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
environment=PYTHONUNBUFFERED=1
stdout_logfile=/dev/null
stderr_logfile=/dev/null
