apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-auth
    namespace: ntfy
type: Opaque
stringData:
    auth.yml: ENC[AES256_GCM,data:hDJ6/HrquF+bt/r1FmAM7biFS7ghmYcMXHB8nPSVNqRlrpB7XNYloBCeeAaSAHE09bEiy9rD3Uzm,iv:7vbx6xbXak8pLIju0sDjh3kDwRKgzy+KCpE+39b1E8I=,tag:4r1EqP4zsyfxGHw5AC7fxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UEM5YUZJOHMvT2Z4MHho
            dWV6WnhncTIwNkJvMlB4bW02VUhlWmd4WlI4CmoxcjJLZ3FCRU5JQlh4UiswUTkr
            T1FoVFN3ME1NaUVmdXpXMW1LSnc3N3MKLS0tIDBvYk41SFZyVWc3Yit1bUlWZUlK
            dUo1dmF4YzVzVXRvL1BtYlFpdmZLNHMKYNZnUQQnbe9e/YF7l6CMj9RbtBia25/V
            EzgYALMccCTtIzkVIH+R3JoO2hWNtv4cECJugTZhbuAZiWECneWfjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T23:03:43Z"
    mac: ENC[AES256_GCM,data:fwp7QRwR/hrmS4EhdKOHu+ICFQ98siywpawNoCCjcYwcoOEYyXlnPpDX7O+bOLBb30fG1tYEk6mvzHU6/y/gnzqLpam2qg/oSMfJtIXOuH+OOb/uwP8q5l8dzhvgyHlWf5jsm51FZWdwVx77ErcW0bAm7QDG1BzjfFc8c4zfs4s=,iv:pNePcwTKwUZCW/jTI4i+kCaV0KvM8BHagvJkG6iXZxs=,tag:PA8BxAIHEnw9C6wt0jNqQA==,type:str]
    version: 3.13.2
