"""Conservative comparison of readable OpenBao 2.7 API configuration."""

import re

from .configuration import Difference, ObjectSpec, SafeError, canonical_json, strict_json

# Every accepted live key is reviewed for its endpoint. New upstream keys fail closed.
FIELDS = {
    "auth-method": {
        "type",
        "description",
        "config",
        "local",
        "seal_wrap",
        "external_entropy_access",
        "options",
        "accessor",
        "uuid",
        "plugin_version",
        "running_plugin_version",
        "running_sha256",
        "deprecation_status",
    },
    "secret-mount": {
        "type",
        "description",
        "config",
        "local",
        "seal_wrap",
        "external_entropy_access",
        "options",
        "accessor",
        "uuid",
        "plugin_version",
        "running_plugin_version",
        "running_sha256",
        "deprecation_status",
    },
    "jwt-config": {
        "oidc_discovery_url",
        "oidc_discovery_ca_pem",
        "bound_issuer",
        "jwt_validation_pubkeys",
        "jwt_supported_algs",
        "jwks_url",
        "jwks_ca_pem",
        "default_role",
        "provider_config",
        "namespace_in_state",
    },
    "jwt-role": {
        "role_type",
        "bound_audiences",
        "bound_subject",
        "bound_claims",
        "bound_claims_type",
        "user_claim",
        "user_claim_json_pointer",
        "groups_claim",
        "claim_mappings",
        "oidc_scopes",
        "allowed_redirect_uris",
        "verbose_oidc_logging",
        "clock_skew_leeway",
        "expiration_leeway",
        "not_before_leeway",
        "token_ttl",
        "token_max_ttl",
        "token_explicit_max_ttl",
        "token_period",
        "token_policies",
        "token_bound_cidrs",
        "token_no_default_policy",
        "token_num_uses",
        "token_type",
        "policies",
        "ttl",
        "max_ttl",
        "period",
        "num_uses",
        "bound_cidrs",
        "max_age",
        "namespace",
    },
    "userpass-user": {
        "policies",
        "token_policies",
        "token_ttl",
        "token_max_ttl",
        "token_period",
        "token_explicit_max_ttl",
        "token_no_default_policy",
        "token_num_uses",
        "token_type",
        "token_bound_cidrs",
        "ttl",
        "max_ttl",
        "period",
    },
    "policy": {"policy", "name", "modified", "version", "cas_required"},
    "kubernetes-config": {
        "kubernetes_host",
        "kubernetes_ca_cert",
        "disable_local_ca_jwt",
        "service_account_jwt",
        "disable_iss_validation",
        "token_reviewer_jwt",
    },
    "issuance-role": {
        "allowed_kubernetes_namespaces",
        "allowed_kubernetes_namespace_selector",
        "service_account_name",
        "kubernetes_role_name",
        "generated_role_rules",
        "token_default_ttl",
        "token_max_ttl",
        "token_default_audiences",
        "extra_annotations",
        "extra_labels",
    },
}

# These fields are generated by the server, not configuration controls.
VOLATILE = {
    "auth-method": {
        "accessor",
        "uuid",
        "running_plugin_version",
        "running_sha256",
        "deprecation_status",
    },
    "secret-mount": {
        "accessor",
        "uuid",
        "running_plugin_version",
        "running_sha256",
        "deprecation_status",
    },
    "policy": {"modified", "version"},
}
DEFAULTS = {
    "jwt-role": {
        "role_type": "jwt",
        "bound_claims_type": "string",
        "token_type": "default",
        "token_num_uses": 0,
        "token_period": 0,
        "token_explicit_max_ttl": 0,
        "user_claim_json_pointer": False,
        "verbose_oidc_logging": False,
    },
    "auth-method": {
        "description": "",
        "local": False,
        "seal_wrap": False,
        "external_entropy_access": False,
        "options": None,
        "plugin_version": "",
    },
    "secret-mount": {
        "description": "",
        "local": False,
        "seal_wrap": False,
        "external_entropy_access": False,
        "options": None,
        "plugin_version": "",
    },
    "issuance-role": {
        "allowed_kubernetes_namespace_selector": "",
        "kubernetes_role_name": "",
        "generated_role_rules": "",
        "token_default_audiences": [],
        "extra_annotations": {},
        "extra_labels": {},
    },
}
SETS = {
    "bound_audiences",
    "token_policies",
    "policies",
    "allowed_kubernetes_namespaces",
    "token_default_audiences",
    "jwt_supported_algs",
    "jwt_validation_pubkeys",
    "token_bound_cidrs",
    "bound_cidrs",
    "oidc_scopes",
    "allowed_redirect_uris",
}
DURATIONS = {
    "token_ttl",
    "token_max_ttl",
    "token_default_ttl",
    "token_explicit_max_ttl",
    "token_period",
    "ttl",
    "max_ttl",
    "period",
    "clock_skew_leeway",
    "expiration_leeway",
    "not_before_leeway",
    "default_lease_ttl",
    "max_lease_ttl",
}
BOOLEANS = {
    "token_no_default_policy",
    "disable_local_ca_jwt",
    "disable_iss_validation",
    "force_no_cache",
    "local",
    "seal_wrap",
    "external_entropy_access",
    "user_claim_json_pointer",
    "verbose_oidc_logging",
    "namespace_in_state",
    "cas_required",
}
STRINGS = {
    "type",
    "description",
    "oidc_discovery_url",
    "bound_issuer",
    "default_role",
    "bound_subject",
    "user_claim",
    "role_type",
    "token_type",
    "service_account_name",
    "kubernetes_role_name",
    "generated_role_rules",
    "kubernetes_host",
    "allowed_kubernetes_namespace_selector",
    "groups_claim",
    "jwks_url",
    "bound_claims_type",
    "kubernetes_ca_cert",
}
DICTS = {
    "provider_config",
    "bound_claims",
    "claim_mappings",
    "extra_annotations",
    "extra_labels",
    "options",
    "user_lockout_config",
}
_DURATION = re.compile(r"(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?")


def _seconds(value: object) -> int:
    if type(value) is int and value >= 0:
        return value
    if isinstance(value, str):
        if value.isdecimal():
            return int(value)
        match = _DURATION.fullmatch(value)
        if match and any(group is not None for group in match.groups()):
            hours, minutes, seconds = (int(group or 0) for group in match.groups())
            return hours * 3600 + minutes * 60 + seconds
    raise SafeError("invalid-response")


def _policy(value: object) -> dict:
    if isinstance(value, str):
        value = strict_json(value, "invalid-policy")
    if (
        not isinstance(value, dict)
        or set(value) != {"path"}
        or not isinstance(value["path"], dict)
    ):
        raise SafeError("invalid-policy")
    for path, rule in value["path"].items():
        if (
            not isinstance(path, str)
            or not isinstance(rule, dict)
            or set(rule) != {"capabilities"}
            or not isinstance(rule["capabilities"], list)
            or not all(
                isinstance(cap, str)
                and cap in {"create", "read", "update", "delete", "list", "sudo", "patch", "deny"}
                for cap in rule["capabilities"]
            )
        ):
            raise SafeError("invalid-policy")
    return {
        "path": {
            path: {"capabilities": sorted(set(rule["capabilities"]))}
            for path, rule in value["path"].items()
        }
    }


def _normalized_value(key: str, value: object) -> object:
    if key == "policy":
        return _policy(value)
    if key in DURATIONS:
        return _seconds(value)
    if key in BOOLEANS:
        if type(value) is not bool:
            raise SafeError("invalid-response")
        return value
    if key in STRINGS:
        if not isinstance(value, str):
            raise SafeError("invalid-response")
        return value
    if key in DICTS:
        if key == "options" and value is None:
            return None
        if not isinstance(value, dict):
            raise SafeError("invalid-response")
        return value
    if key in SETS:
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise SafeError("invalid-response")
        return sorted(set(value))
    if key == "config":
        if not isinstance(value, dict):
            raise SafeError("invalid-response")
        allowed = {
            "default_lease_ttl",
            "max_lease_ttl",
            "force_no_cache",
            "token_type",
            "audit_non_hmac_request_keys",
            "audit_non_hmac_response_keys",
            "listing_visibility",
            "passthrough_request_headers",
            "allowed_response_headers",
            "allowed_managed_keys",
            "identity_token_key",
            "user_lockout_config",
        }
        if set(value) - allowed:
            raise SafeError("invalid-response")
        return {field: _normalized_value(field, item) for field, item in value.items()}
    if isinstance(value, (dict, list)):
        return value
    if value is None or isinstance(value, (str, bool)) or type(value) is int:
        return value
    raise SafeError("invalid-response")


def normalize(spec: ObjectSpec, data: dict) -> dict:
    if not isinstance(data, dict) or spec.kind not in FIELDS:
        raise SafeError("invalid-response")
    if set(data) - FIELDS[spec.kind]:
        raise SafeError("invalid-response")
    normalized = {}
    for key, value in data.items():
        if key in VOLATILE.get(spec.kind, set()):
            continue
        normalized[key] = _normalized_value(key, value)
    for key, value in DEFAULTS.get(spec.kind, {}).items():
        if key in spec.fields:
            normalized.setdefault(key, value)
    return normalized


def compare(spec: ObjectSpec, data: dict | None | SafeError) -> list[Difference]:
    if data is None:
        return [Difference(spec.kind, spec.name, None, "missing")]
    if not isinstance(data, dict):
        return [Difference(spec.kind, spec.name, None, "inaccessible")]
    findings = []
    unknown = set(data) - FIELDS.get(spec.kind, set())
    if unknown:
        findings.append(Difference(spec.kind, spec.name, None, "unexpected"))
    for key in sorted(
        set(data)
        & FIELDS.get(spec.kind, set()) - set(spec.fields) - VOLATILE.get(spec.kind, set())
    ):
        default = DEFAULTS.get(spec.kind, {}).get(key, object())
        try:
            current = _normalized_value(key, data[key])
        except SafeError:
            current = object()
        if current != default:
            findings.append(Difference(spec.kind, spec.name, key, "unexpected"))
    for key, expected in sorted(spec.fields.items()):
        if key not in FIELDS.get(spec.kind, set()):
            findings.append(Difference(spec.kind, spec.name, None, "inaccessible"))
            continue
        live = data.get(key, DEFAULTS.get(spec.kind, {}).get(key, object()))
        if type(live) is object:
            findings.append(Difference(spec.kind, spec.name, key, "inaccessible"))
            continue
        try:
            actual_value = _normalized_value(key, live)
            expected_value = _normalized_value(key, expected)
            if canonical_json(actual_value) != canonical_json(expected_value):
                findings.append(Difference(spec.kind, spec.name, key, "changed"))
        except SafeError:
            findings.append(Difference(spec.kind, spec.name, key, "inaccessible"))
    return findings


def compare_inventory(expected: set[str], actual: set[str], kind: str) -> list[Difference]:
    if (
        kind not in FIELDS
        or not isinstance(expected, set)
        or not isinstance(actual, set)
        or not all(isinstance(v, str) for v in expected | actual)
    ):
        raise SafeError("incomplete-list")
    findings = [Difference(kind, name, None, "missing") for name in sorted(expected - actual)]
    count = len(actual - expected)
    if count:
        findings.extend(Difference(kind, None, None, "unexpected") for _ in range(count))
    return findings


def sanitize(differences: list[Difference]) -> dict:
    output = []
    extra = {}
    for finding in differences:
        if finding.kind not in FIELDS or finding.state not in {
            "missing",
            "changed",
            "unexpected",
            "inaccessible",
        }:
            raise SafeError("invalid-response")
        if finding.name is None:
            if finding.state != "unexpected" or finding.field is not None:
                raise SafeError("invalid-response")
            extra[finding.kind] = extra.get(finding.kind, 0) + 1
            continue
        item = {"kind": finding.kind, "name": finding.name, "state": finding.state}
        if finding.field is not None:
            if finding.field not in FIELDS[finding.kind]:
                raise SafeError("invalid-response")
            item["field"] = finding.field
        output.append(item)
    for kind, count in sorted(extra.items()):
        output.append({"kind": kind, "state": "unexpected", "count": count})
    return {"differences": output}
