apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: openbao-reader-code
    namespace: openbao
    files:
      - __init__.py
      - configuration.py
      - drift.py
      - verify.py
      - exporter.py
