apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./serviceaccount.yaml
  - ./cronjob.yaml
  - ./ciliumnetworkpolicy.yaml
configMapGenerator:
  - name: openbao-snapshot-script
    namespace: openbao
    files:
      - snapshot.py=./scripts/snapshot.py
generatorOptions:
  disableNameSuffixHash: true
