apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbao-backup
  namespace: openbao
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
