apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openbao
  namespace: openbao
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao
      app.kubernetes.io/instance: openbao
      component: server
