---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./cronjob.yaml
  - ./persistentvolumeclaims.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
  - ./statefulset.yaml
configMapGenerator:
  - name: n8n-postgresql-init
    files:
      - init-database.sh=scripts/init-database.sh
  - name: n8n-postgresql-backup
    files:
      - backup.sh=scripts/backup.sh
      - update-backup-status.sql=scripts/update-backup-status.sql
  - name: n8n-postgresql-sql-exporter
    files:
      - sql-exporter.yml=sql-exporter.yml
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
