apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: automation
type: Opaque
stringData:
    postgres-superuser-password: ENC[AES256_GCM,data:7TrTGMQtMR+2OFtOkUrRJHqvE/QWCMx+qxPlZqHLiWruCrBB8klRpw==,iv:geb7ven/MhRG93gCztCZDHsTW/qq3vyGdhEg/oVCmP8=,tag:FA7vq+GE7Q/TYKdnZccOAQ==,type:str]
    n8n-password: ENC[AES256_GCM,data:klAFCeaSseOQ7+1wMewivqz6x6R2IMC3fBND+1OlwqHZUap9XsB+Cw==,iv:bSwDLH/BiA5wJeoNyUtkwLz0TJcP8+dlL8vAdhsqpiA=,tag:WklkyCWVERM8LFG6ShV8QA==,type:str]
    backup-password: ENC[AES256_GCM,data:XIq5MqIGt7wnwTHqQVrygn6GsMVrP7QtT3TEFzHXTcsRyrPTPrh2tQ==,iv:67kD7avN8dy2ztNZn+Y4d4v2iM+etk0UxesxIFCGADs=,tag:dNoarUk4ZfYE8ixj3woCGw==,type:str]
    exporter-password: ENC[AES256_GCM,data:hDudnABKmTgHY5PkdJgJt55cTUKhpcdB44+0OUtyXkwVY6MTp4AknQ==,iv:Lka2yseywX2hIPvnQc26qBWERtW1sE35H9LW86wCjss=,tag:AbALtFwuGYo9fCt7xR5PsA==,type:str]
    exporter-dsn: ENC[AES256_GCM,data:jfnnvgTxzd/QWW9zEv22niAFuk/PIolrMCsxjfsAOblCt+07bkzCHbq+fM9prTGMejcA1Nca4gI1zYcb0XZ16fr9YKvQlYdc7khRgzBAkLFs72BUx8FkDMM7WD5qM5uAjDPhXa5lQ6ncBIsK1U5lW3/gOg==,iv:9AV3OdKiRlJJQ8L4rIWXbh77Z4crWnP2dBpudBeo/kA=,tag:janQupICBNxLOzHE7DxMmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYnNZVFhscER4bDJHU0lW
            cmRVcEsrUktKeGRWS0NGMHlIRnlCMndDWDBRCm5EZFQxanlkQ1hMSUtsVE1UcDdl
            TUJoMVRYSXlVK3l3WTNzM1FoNXh0aEUKLS0tIFppVCs3UFhYQldGVmhYa1FCb0xI
            anZLTGpENjdvT1lZclNqQ0VkSkNCQjgKPFDwwtmIGtQJvD8Rd9e7wc3fR0KbHJ61
            M1eNvMmuqZ5NISlV9LgiPXGtUofQQcYGIX2JjsrrKSitjF4Xn59OvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T16:27:40Z"
    mac: ENC[AES256_GCM,data:6Xw/spwo93fHgqtqLHGn61uIsI4kF9mOmvScHZL84pA9fgvDF8iJszoZ6UxMsg+G/J9tePXDuGenOki6eXaWVwptxJb3kmMQiU0m06C7tCdmhA1UStnrNw87R/Kx2POGsTWXH0vhfbAj71DWSvPcDVynHVxDjMVNNlv0I0UUqIo=,iv:zTwNrhrRj6UcaDecFRQLGu4yWua9IWCETYpk0Y+KbP4=,tag:v0H5hD3n21f0WlqzpXNNEQ==,type:str]
    version: 3.13.2
