---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./deployment.yaml
  - ./httproute.yaml
  - ./namespace.yaml
  - ./persistentvolumeclaim.yaml
  - ./service.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: test-reports-config
    namespace: test-reports
    files:
      - Caddyfile=Caddyfile
      - bootstrap-storage.sh=bootstrap-storage.sh
      - install-report.sh=install-report.sh
  - name: test-reports-dashboard
    namespace: test-reports
    files:
      - dashboards/test-reports.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
