---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-reports
  namespace: test-reports
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
