apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web-research
resources:
- ./deployment.yaml
- ./services.yaml
- ./ciliumnetworkpolicy.yaml
- ./servicemonitor.yaml
- ../runtime
- ./bootstrap.sops.yaml
