---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb
  namespace: automation-data
spec:
  chartRef:
    kind: OCIRepository
    name: nocodb-chart
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  interval: 1h
  releaseName: nocodb
  timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: nocodb-values
      valuesKey: values.yaml
