---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation-data
resources:
  - ./ciliumnetworkpolicy.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./metadata-bootstrap-job.yaml
  - ./ocirepository.yaml
  - ./nocodb-credentials.sops.yaml
configMapGenerator:
  - name: nocodb-test-helpers-v1
    options:
      immutable: true
    files:
      - test-helpers/nocodb-restore-request.mjs
  - name: nocodb-values
    files:
      - values.yaml=values.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
