apiVersion: v1
kind: Secret
metadata:
    name: nocodb-credentials
    namespace: automation-data
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:bbYEDKimFMCXvgCtqSXjfBI0bvq7thjEbNZoOH8eKpdKznbMsUx7BaD6eEqc34DTOTRE+UfeWuyhrIy4zV4y2XG2wAQ2gEuFq4wMHa4EDNubMhpp4m2n5m2tys1lFb1+5MZNZ5K2M7KZ3rjsUKYscxeju/PHri920m6ZNGJStcIhDu3+ie/7H5mT27tasbvjU71TNWzBHd3XTvU3w6TfVEjsgnM=,iv:c4CcDBCR1IWBFX3zMVrJg6/rTnkvwzjHK0E/2RgO7FE=,tag:3PqKccUIJyXi8qh2VQAP7g==,type:str]
    metadata-password: ENC[AES256_GCM,data:zM6nWaC49M4H0XS6WeqcnKGRpZKWvcFqOSfmJqGDQMXu8uBy4f2oPQ==,iv:AdMsZ0wjG+HQndk0UQVv3rClQLZZAcwzT5b9G40OxPo=,tag:755nY43qh1gxCwY+qpym8g==,type:str]
    NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:hiP2FlIHREG8CGVonZRvBK++vF0ct8IjN/7HsP832j8bQJqi0sGpBQ==,iv:PkZTrxzVDIqnD+Ofy8x/oTLqzGYG0Vwp2qID/KuM/CY=,tag:FI7lpiaYYflWBS3WA0hF+w==,type:str]
    NC_CONNECTION_ENCRYPT_KEY: ENC[AES256_GCM,data:HBA7ckwn4k5h3IP45wSJoyBuuuJ4qVWZyzx5U7H8oNylXP4r3HJ9hA==,iv:4Gy1JAJ9pHeqtqX+NlFvnN9495LW3H+FNdVZp3pBZNA=,tag:IwXvhtIBs+ETetIN26k9Ag==,type:str]
    NC_ADMIN_EMAIL: ENC[AES256_GCM,data:VbCJ8HPS+CJDMXVDtMYokf6B3ercKXUinik0ShclMg==,iv:ldZd5ShvAH8gWIq0ArxK0tCTPOnNTPrJfW4+oqmW8aE=,tag:A2DptZERQnjme+fNedf9sg==,type:str]
    NC_ADMIN_PASSWORD: ENC[AES256_GCM,data:+29nMj0DFnFgwr1++88lA1z8V9SKr9jhHZSodFhpKQYi81K/3GDKIQ==,iv:9vSiPOrQswiX1BQ8UTcqnUbX7vGcwjumRM0fWRg0m8A=,tag:jZHkUxWetIGhVT9XfZiKLg==,type:str]
    source-provisioning-header: ENC[AES256_GCM,data:shttWYeBw3CPMS8WLkti+chSAsBvjjUXJL/DlsjumZGSN8pb/UTgKw==,iv:gM7QWEdplu13s6jEsThiVrNqZ0OibUSdGNgNUZeeJ6Y=,tag:bOW6ET1PQb89fz+ZdIRZtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR1BQend3VlFJZEFkNTZo
            ZGU1QklYTjBUZFBLczhYWnByYUJJcHkwTFJZClJ3SWprejlIWWxVelZOajZKSEc0
            MUZ5QmdKVnNLU2xjME1Gcmc5bXphN1EKLS0tIDVKdm9UVUQvT2M0Z2JUeHFmMTUw
            SzVaU3M1d29vbGphTWx1N0h1OHBYT0kKjHmQeFjZ9P3cNDT+ZfprcuGLjpJTNjb0
            SK8NwNvnjZYxCSBVAslhFoKGC4eT6zO9mMjv1t10ob4H/ECh3l0GrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T11:03:24Z"
    mac: ENC[AES256_GCM,data:dGbR/56MWXbZtYBIiAT3WcX4hOW7TGJCEn2m2dnuK4r6AR+RbOqeo7DG6iCxV2V9jeXZEwOhnhDyu36habm7Lalb3LAPjGpKksSDi+qFYZRKAGXz2OqKrr9+Ci4xZukojQg6OMPsGlvrkq8uU1ttf+vZuw80ygjdhHsytet1v8M=,iv:b7wl74LE4vD75pUd1Lwdd7iUPvFfJGz0CMTBBKtiqyo=,tag:oQ9bjXgbZ4Ia7GbrBbXT+Q==,type:str]
    version: 3.13.2
