---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nocodb-chart
  namespace: automation-data
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:b2aa331863ec002e5001db33c2ac257bc0f1df690396c340e3e38e6978fece6c
  url: oci://ghcr.io/nocodb/charts/nocodb
