apiVersion: v1
kind: Secret
metadata:
    name: homepage-portainer
    namespace: homepage
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:fD9lgMRK5N43hxbNwRsaYVSJASRC5qrX+tNGI8TAy1bPGmAPqty82EHoHBiSxTbj,iv:wX2xjco44xwPhS2JbUit192Po0bo1lQm7L6xaS9Z7h0=,tag:yaSCzObdxArR2tiQEin7bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQUFoK2tibGNETzlhMkVJ
            ODFMc1hlSUlkVUZKeEhyQnZsVWo4TytBM1U4Cmx2SkhuakxNeFl4S0Fab1dkUDh2
            MWtOaUdjVWRpeWZrT0ozY0pIYkVDMXcKLS0tIFFleEdVa1ZPVGxVUTJmTFIyb1o4
            VWUraFdNTWlOV2FyV29ybkE2dzUvL0UKFUIEeAzsMVdjJYQpj7+nWypHH9wxFGZE
            0MqC12UhGzJfB3M86tr0fEuixLvuoioQ8V0bph00m1sk96n+36ZsRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T02:23:25Z"
    mac: ENC[AES256_GCM,data:2hLIBOvTYqKtNMf8zHzdeWcvXwnIWB51R2zjKpUasCqcVDggr2N+dguhyTtdqse5LzxPwenMLvaFehmwmctf7JO4dx1WZ1jvmYo9SJW6D/+z9plWHfnr9caPz5Sv+k1noGg7Yx0yQlCzyk4bYiXln2YHqRFuFsOd92nTFr0nDcU=,iv:wt1mXtkkFZYUFbmWwrpkS9othERtZ7fZbiGk7fPU+ZY=,tag:AnQOLtl1SpBammfgM3Yg7g==,type:str]
    version: 3.13.2
