apiVersion: v1
kind: Secret
metadata:
    name: homepage-grafana
    namespace: homepage
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:nDVEG4w=,iv:5gUZEq2DYemS8dSBAP1hFwIobSRSv9qYfIn1IPyJaKs=,tag:VK2OvuXb3twCIK5cbAK+Tw==,type:str]
    password: ENC[AES256_GCM,data:Glmh0TVMLEnXp3QAicsoLjuqjuQsJxu0uE3hKCnN7OtX8GfhXdCWHQ==,iv:QG7funr9HZlfH7lveJ4fidjOnPgzpeJb8Mkre2L56Go=,tag:M2VEMGzwrNc6042VrzNigw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa0FybVB0TkJSMENROW55
            Vll2SVd0cXNiUjk4OEpHWUFRRGFadG5CM0N3CnNCYXdydnRUU1JFditCSzZoMHdG
            TWJvSXVtWVdGbzNWQmV6Q3ZIZmtrYkkKLS0tIGxPVGpTR3ZJVEdRT1Ntdi9aOGN4
            SE1qa1NaMjEwMENRTTRnOFJXajJnSWsKvw8ohj90nTRp6LTkV965Z+SOSa5veLRa
            yLQvYyjJc/FCpumUb19RDioSJ12d3emm/3HTFQjPxRnnTiXaPPZrqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T13:48:38Z"
    mac: ENC[AES256_GCM,data:DA5L5fFCYFoXkrRS4YiECVc2dPQvmEdmuVQYdtG1pSo+0cdNk5+bxP9qRqX2E1SFS/txtFUW8sVtsj63BcPbNViP8FiuWdbCmNyQ5iCHy2sAnvDp9PhdTQgKbjb9f6xvedWma+HUQ0wnNHtcFWjS7ycbsxMlfmDn/IQQNWY9H6U=,iv:yzygiEqBV1G6Hk/zBY6pHfAEZ5AqIYx/jmnQefZ38nY=,tag:vuAOBmDeUPXQdMT2mNmq5g==,type:str]
    version: 3.13.2
