---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./homepage-grafana.sops.yaml
  - ./homepage-plex.sops.yaml
  - ./homepage-prowlarr.sops.yaml
  - ./homepage-qbittorrent.sops.yaml
  - ./homepage-sonarr.sops.yaml
  - ./httproute.yaml
  - ./namespace.yaml
  - ./rbac.yaml
  - ./service.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    files:
      - settings.yaml=config/settings.yaml
      - kubernetes.yaml=config/kubernetes.yaml
      - services.yaml=config/services.yaml
      - widgets.yaml=config/widgets.yaml
      - bookmarks.yaml=config/bookmarks.yaml
      - docker.yaml=config/docker.yaml
      - proxmox.yaml=config/proxmox.yaml
      - custom.css=config/custom.css
      - custom.js=config/custom.js
