---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: plex-public
  namespace: media
spec:
  hostnames:
    - plex.lab.supermorphic.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: networking-public
      name: public
      sectionName: https
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: plex
          port: 32400
