---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: automation-data-postgresql
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: automation-data-postgresql
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: automation
            app.kubernetes.io/name: n8n
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: automation-data
            app.kubernetes.io/name: automation-data-postgresql-backup
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: prometheus
            operator.prometheus.io/name: kube-prometheus-stack-prometheus
      toPorts:
        - ports:
            - port: "9399"
              protocol: TCP
  egress: []
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: automation-data-postgresql-backup
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: automation-data-postgresql-backup
  ingress: []
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s:k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: automation-data
            app.kubernetes.io/name: automation-data-postgresql
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
