---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation-data
resources:
  - ./cronjob.yaml
  - ./persistentvolumeclaims.yaml
  - ./postgresql-credentials.sops.yaml
  - ./service.yaml
  - ./statefulset.yaml
configMapGenerator:
  - name: automation-data-postgresql-init
    files:
      - init-platform.sh=scripts/init-platform.sh
      - platform-control.sql=scripts/platform-control.sql
  - name: automation-data-postgresql-backup
    files:
      - backup.sh=scripts/backup.sh
      - update-backup-status.sql=scripts/update-backup-status.sql
generatorOptions:
  labels:
    reconcile.fluxcd.io/watch: Enabled
