apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: automation-data
type: Opaque
stringData:
    postgres-superuser-password: ENC[AES256_GCM,data:Qx/tsJThGvYdtmaSdleSWgcQDVg0Ipoj9b/tF4Xa1ZPTVctm3hEgZw==,iv:p+stgqV+B3zF8Y4AhEhijXzes5ahQXA82HsDYJOW1Pk=,tag:Fhq0ma0mHl2leTXcDfIabw==,type:str]
    provisioner-password: ENC[AES256_GCM,data:rL0Qd1MtDIbtz6QBqQOOC+si6QI+8FzTliHD+lWkZ00Gi0JO2azqNA==,iv:/5gAOzYKxXwWr1EZkqgOGoNS1qkmzljH97TXU5wjZSw=,tag:nWc/NGFavIaX+u0of7lkSA==,type:str]
    backup-password: ENC[AES256_GCM,data:jqqhN4/pb1YLdCr9y4HHUn4AUrYUC1ETcKB8Wi/l2P2BJM+1xHD3eQ==,iv:fqhZq3BNp38NNwgdjjGEvmqSPHOogbS3u7KWcqLeOqc=,tag:qX12WhU9W/8pTV7HTIPbZQ==,type:str]
    exporter-password: ENC[AES256_GCM,data:WBnA0GrHbvkxTqlZ1didSjue3vFf7k2qOKjlwNCeynrpi2xqpHmybQ==,iv:w6mwnT5SGSRyaEKcNxCiT23ZYCGbOrRutgck0DeqFvw=,tag:g39nVL1Hn7VU7wq66Qn8kQ==,type:str]
    exporter-dsn: ENC[AES256_GCM,data:1HtJKvZFJ+WMAMAnpExHWi5U/GnQCbYVx5CctOL1XmNWYz1TT7v0w1a9kd2EnIKioOLIP5fsEA0OPOP9OIBusyIr7l/I5dI4bwNIXv2ILNMRYZid2v6gKNoHn2pq5J7USOi3Ia+TNYY9tU7Ym2jQg2q4fK6N0t2GUe5smDS7gdr9tHxHq6AoxgWz9Jil,iv:BRnkykQs7LCPlm9dBHIN7xm8fcpCBej9tW61NUP6ORk=,tag:OsFgxBSOAd6STbPXIuVCfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQkFHWlRLa0lGaTFtMndh
            RnJ1NTdRUzlqanorS0FJelFUTzNZckZoWmxnCjBEdlpFWjhPRXdoU3hKS1d6QUR0
            SjFIRlhrSytnaDVYS09tVy91MmUvM2cKLS0tIGY1VHRwZm8zVVp6VkhCT1Zad1k4
            NEhJVEg2MTduZDJzQlRucHJ3Y1RwV1UKzio18T85MvTryr8TToxED9UKFpkYRbug
            cLG9qLvrv/bu/gxKR24IqCs98MyDWYa4mFz+x77vqfTp479GPQ0Anw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T10:50:55Z"
    mac: ENC[AES256_GCM,data:8jCxY8IbgY/XdRC6/OKda9Qs7UUL9VeZKHE/GyK+d4pCGp99KO66c/O19JQJM4ajJPwKRYfaO0hZgx4C7Yq/JPS7EFMCSxiGLuZ8Ql4JKTzbEWBwO8NU3cF3twqL8Jn+BZrf5WtRVuW7yfNuTDE13NHOHKgWVfcnNwXZHv9W0HI=,iv:T1Y4Z81EFjvV3Tzyat0dGcX1hX7L1bnSVKQyX679nhE=,tag:maOzTO5zMTbcSVvvXaOiWg==,type:str]
    version: 3.13.2
