---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: automation-data-postgresql
  labels:
    app.kubernetes.io/name: automation-data-postgresql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: automation-data-postgresql
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
