---
apiVersion: v1
kind: Service
metadata:
  name: automation-data-postgresql
  labels:
    app.kubernetes.io/name: automation-data-postgresql
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: automation-data-postgresql
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
    - name: metrics
      port: 9399
      protocol: TCP
      targetPort: metrics
