---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal
  namespace: metallb-system
spec:
  addresses:
    - 192.168.90.30-192.168.90.38
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internal
  namespace: metallb-system
spec:
  ipAddressPools:
    - internal
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public
  namespace: metallb-system
spec:
  addresses:
    - 192.168.90.39/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public
  namespace: metallb-system
spec:
  ipAddressPools:
    - public
