---
- Development:
    - Homelab Talos:
        - href: https://github.com/ksiggins/homelab-talos
          icon: github-light.svg
    - Homelab Playbook:
        - href: https://github.com/ksiggins/homelab-playbook
          icon: github-light.svg
    - Dashboard Icons:
        - href: https://github.com/homarr-labs/dashboard-icons
          icon: github-light.svg
- Cloud Services:
    - Cloudflare:
        - href: https://dash.cloudflare.com
          icon: cloudflare.svg
    - Docker Hub:
        - href: https://hub.docker.com
          icon: docker.svg
    - Helm Charts:
        - href: https://artifacthub.io
          icon: artifacthub.svg
    - Public KeyDB:
        - href: http://fvonline-db.bplaced.net
          icon: makemkv.png
- Local Area Network:
    - Unifi Network:
        - href: https://udm.supermorphic.com
          icon: unifi-controller.png
    - Unifi Protect:
        - href: https://protect.supermorphic.com
          icon: unifi-protect.png
    - Unifi Drive:
        - href: https://nas.supermorphic.com
          icon: unifi-drive.png
    - Cable Modem:
        - href: https://192.168.100.1/Login.html
          icon: router.svg
    - Room Alert Monitor:
        - href: https://room-alert.infra.supermorphic.com
          icon: mdi-temperature-fahrenheit-#FFFFFF
