---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: public
  namespace: networking-public
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
      envoyPDB:
        minAvailable: 1
      envoyService:
        annotations:
          metallb.io/address-pool: public
          metallb.io/loadBalancerIPs: 192.168.90.39
        externalTrafficPolicy: Local
        type: LoadBalancer
  telemetry:
    accessLog:
      settings:
        - format:
            type: JSON
            json:
              start_time: "%START_TIME%"
              method: "%REQ(:METHOD)%"
              path: "%PATH(NQ:ORIG_OR_PATH)%"
              protocol: "%PROTOCOL%"
              response_code: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              bytes_received: "%BYTES_RECEIVED%"
              bytes_sent: "%BYTES_SENT%"
              duration: "%DURATION%"
              downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
              x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
              user_agent: "%REQ(USER-AGENT)%"
              request_id: "%REQ(X-REQUEST-ID)%"
              authority: "%REQ(:AUTHORITY)%"
              requested_server_name: "%REQUESTED_SERVER_NAME%"
              upstream_host: "%UPSTREAM_HOST%"
              route_name: "%ROUTE_NAME%"
          sinks:
            - type: File
              file:
                path: /dev/stdout
