---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./datasource.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
configMapGenerator:
  - name: loki-values
    namespace: monitoring
    files:
      - values.yaml=values.yaml
  - name: centralized-logs-dashboard
    namespace: monitoring
    files:
      - centralized-logs.json=dashboards/centralized-logs.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
