apiVersion: v1
kind: Secret
metadata:
    name: qbit-manage-secret
    namespace: media
type: Opaque
stringData:
    QBT_USER: ENC[AES256_GCM,data:63BPup4XuM8Xp8DnwWXJu5uDWBaLPqHYxYM1zx5lT+wL9pL5v89XbVzzlTs9LWB4o/DO1EM=,iv:HuNXtGxBtYPaoIwpvjld+DjKvDT60xr5Jc2/Ek0Dhfw=,tag:57vs1cP5HaA3Gzg9zBnNjg==,type:str]
    QBT_PASS: ENC[AES256_GCM,data:Mlj5PKgWk9njlkz9p1G7y0fTRbWNXl1LTSGu0xsbUfaEPV3asAH5CtGc4hFYXKC7KgSS9cE=,iv:qNonfTDqxsg2KOJOwpbBlvhVxB27WhzOlVkaqH3sEpI=,tag:tjKki1l4EZzcWa+YjPSl6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURmZGMFNzbEVjMmtTdEtJ
            QndzLzZucU9TNXEweTRRWWwvY2hIenVGajBjCmh6QnRRbmpCYm5neGJSYjNOcEpp
            Tm5oU0M0clYzQWJ2M1N0TU40Mkl1Qm8KLS0tIEZtK2svc0owc1ZTT2Z2SGJicWlk
            eFRCUVBTaUMvZXk4VDZvdnM1WmNkSWMKWnVSEE05VPKO//ZjRGSBGuBmCzF+WlzL
            lb3JF2E2ZwiXHUNzCCdiIzWxmMuZuf9wonifN9nzz5Tyjl8blSD3pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T00:59:55Z"
    mac: ENC[AES256_GCM,data:Md8ca06/7zAuroy0+PIyHeuEZGwc16Lf0stGn5NXtQbpxwGG4VXsiTKVKHkiONWqZM7q3cXNGljcMc9krupN4mX83u41KdbNNN5v4B3oOQCsf3/ugpzlBN6Wt/Aj26VoBkC0UT1Ozhk74v/CwrCe/EqMiOnkFudXnb7eUCBE+Z0=,iv:aRdW1tfe7Y4VpdOC/H4yuoC/UaqJ4YHztC5yGwrN/Wo=,tag:cM63SvV1w/GmYsEw5/G5dQ==,type:str]
    version: 3.13.2
