apiVersion: v1
kind: Secret
metadata:
    name: qbit-manage-secret
    namespace: media
type: Opaque
stringData:
    QBT_USER: ENC[AES256_GCM,data:Kyx/SMA=,iv:a1RPwoxXsLM6glEuXZbxDr/CIfrcNOoCY9Ukb0+rkEs=,tag:Q5LHCPHp6leJ+FuNLzewKA==,type:str]
    QBT_PASS: ENC[AES256_GCM,data:ljl2oDrbqOXg4fdPx6g4muikgE0p6Yq3mbMr0eKX7pYJVC8D6loYew==,iv:182b6E+v2FHN5QlOIQTPjGxTnZKF6ICcifriW5CHi1o=,tag:ot9FWVkn8kU21jwXU33xPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN1JBOVJsYUwyc0FEQzAx
            ZmZQanlsME5BVllPRFU0R2lQbUJ1QUpXdTNnCk44QjFyVkFuTmJVdzZRTGV0Q2Z2
            bHZSanNKeUVhb25pdjNjZFpqVUROTlUKLS0tIFIvRzZIb1dFdmM2c3NRSlFMWTk5
            ekl3K3pPK3JFbkJkK3FMa3N6TE9DN1kKp05VUBVZ4wCeni6s43e17QHlSSsejCiz
            O5jGLyr+8jLMCkq9BCJClMtIrWs7Vygpl+VnRnPmCaQrNrd5QTMMzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1da2cywfkg9hp6v39jvj9qcmqz4n8w3gm6nqj5vygu7e0zzgnp5psne9wlx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T01:27:54Z"
    mac: ENC[AES256_GCM,data:hsXcEA09HEweo1UcWgJXFMiFGmeaZ4+12K+QDSwzGcvtOrGHC0RH9qkNOz0tCo+vmDo3SbSTAGGKVhfGVVpOniK4wJhzEj5fcFO9YY/lUXcelEywESQAUz9Iw2RaPZG797MdL/8l3AVp3WIhA9ohWcPQr0fY80/C15fW1hRzbL8=,iv:TnSB3O68vpg52R8yuwcMx3T25oleGSQO+TVpFc0JABM=,tag:H7UKzxGrT8AZDdmRBBLtkw==,type:str]
    version: 3.13.2
