---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./automation
  - ./automation-data
  - ./flux-system
  - ./kube-system
  - ./media
  - ./monitoring
  - ./networking
  - ./security
  - ./storage
  - ./testing
