---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./priorityclass.yaml
  - ./samples.yaml
configMapGenerator:
  - name: encode-benchmark-scripts
    files:
      - probe.sh=scripts/probe.sh
      - census.sh=scripts/census.sh
      - runmeta.sh=scripts/runmeta.sh
      - benchmark.sh=scripts/benchmark.sh
      - stills.sh=scripts/stills.sh
generatorOptions:
  labels:
    app.kubernetes.io/name: encode-benchmark
