---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: news-recovery-test
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: longhorn
  interval: 1h
  path: ./kubernetes/apps/news/recovery/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  suspend: false
  timeout: 5m
  wait: true
