apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao
  namespace: openbao
spec:
  secretName: openbao-tls
  dnsNames:
    - openbao.lab.supermorphic.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  usages:
    - digital signature
    - server auth
