apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: openbao
  namespace: openbao
spec:
  targetRefs:
    - {group: "", kind: Service, name: openbao}
  validation:
    hostname: openbao.lab.supermorphic.com
    wellKnownCACertificates: System
